steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/roi:$COMMIT_SHA',
    '-f', 'Dockerfile',
    '.'
  ]
  timeout: 1200s

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/roi:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'roi',
    '--image=gcr.io/$PROJECT_ID/roi:$COMMIT_SHA',
    '--cpu=4', '--memory=16Gi',
    '--region=us-central1',
    '--service-account=$SERVICE_ACCOUNT',
    '--set-env-vars', 'PORT=8000'
  ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/roi:$COMMIT_SHA'
